// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-5HZSXO6bHbz4d4UOMpw5UkLrXJnkvk4',
    appId: '1:125351721048:android:8bc3565691f31695fa722d',
    messagingSenderId: '125351721048',
    projectId: 'vibevent-e9dd7',
    storageBucket: 'vibevent-e9dd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN-pi5KlPclRi6KKskewx7-koSrtQC1CU',
    appId: '1:125351721048:ios:afa7132f3262bb13fa722d',
    messagingSenderId: '125351721048',
    projectId: 'vibevent-e9dd7',
    storageBucket: 'vibevent-e9dd7.firebasestorage.app',
    iosBundleId: 'com.example.vibevent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCocqAzyCqKNvL-iZTNVh62DUnv-muoRZA',
    appId: '1:125351721048:web:498c2158d166ea55fa722d',
    messagingSenderId: '125351721048',
    projectId: 'vibevent-e9dd7',
    authDomain: 'vibevent-e9dd7.firebaseapp.com',
    storageBucket: 'vibevent-e9dd7.firebasestorage.app',
    measurementId: 'G-0NB0EPW03V',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCocqAzyCqKNvL-iZTNVh62DUnv-muoRZA',
    appId: '1:125351721048:web:498c2158d166ea55fa722d',
    messagingSenderId: '125351721048',
    projectId: 'vibevent-e9dd7',
    authDomain: 'vibevent-e9dd7.firebaseapp.com',
    storageBucket: 'vibevent-e9dd7.firebasestorage.app',
    measurementId: 'G-0NB0EPW03V',
  );

}